version: '3.8'

services:
  frontend:
    container_name: ethdashboard-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      VITE_PORT: 8080
  
  backend:
    container_name: ethdashboard-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      MONGO_URL: "mongodb://ethdashboard-mongo:27017/ethdashboard"
      PORT: 5000
      ETHERSCAN_API_KEY: "XN7FQRFD23YWACX1CTMBDRNYTFRG5M1SHI"
    ports:
      - '5000:5000'
    depends_on:
      - ethdashboard-mongo
  ethdashboard-mongo:
    container_name: ethdashboard-mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongoDB:/data/mongo

volumes:
  mongoDB: